### ISSUE TITLE
Faintly visible Settings sliders/Text in Highlighted fields

### ISSUE THREAD

**Issue by DrDanielus** [BingBongBonky/SpaceHUD#10]
Having now spent a whole day playing TF2 with your hud I have to say, I really, really like it. I might even finally ditch ToonHud after 6 years. (has it really been that long‽)
### uhm, anyway
I have noticed that certain UI elements seem to blend into one another due to a lack of contrast, which makes them very difficult to see. It mainly applies to the **Settings sliders** and **Text in fields that become highlighted when hovering over them**.

- For reference I have attached an image that shows two pairs of comparison shots between your hud and TF2's default one (the mouse cursor is in the same place in each pair)

![SpaceHUD Settings](https://user-images.githubusercontent.com/95301600/147979899-9246632b-b292-4824-ab4a-dcd377b45ecb.png)

Other than that, no other issues to report. I'll be on the lookout and keep you posted when I find anything else.

**Comment by BingBongBonky** [comment]
Should be fixed now. Thanks.
