### ISSUE TITLE
Button for switching from taunts to loadout itself is in the wrong place

### ISSUE THREAD

**Issue by xcd859** [BingBongBonky/SpaceHUD#12]
![image](https://user-images.githubusercontent.com/97279652/148510267-12271de7-5a5f-4fd6-8d6d-b0c07e6637aa.png)

**Comment by BingBongBonky** [comment]
What resolution are you on and how often does this happen

**Comment by xcd859** [comment]
Standard 1920x1080 16:9 resolution, it happens every time i open my loadout for all classes

**Comment by BingBongBonky** [comment]
Thats weird, this doesn't happen to me at all. I had that issue if I switched resolutions while in game but not while booting in.

**Comment by BingBongBonky** [comment]
Since theres been no response Ill mark as not an issue and close unless someone else has it as well
