### ISSUE TITLE
Suggestion for casual/competitive badge switch

### ISSUE THREAD

**Issue by olib14** [BingBongBonky/SpaceHUD#19]
![Screenshot_20230723_015108](https://github.com/BingBongBonky/SpaceHUD/assets/107320647/fd79519e-11db-41cf-94d8-64332c641412)

This button is incredibly small compared to the other buttons. If at all possible, have the 'Casual'/'Competitive' string to the right of the badge act as a dropdown (and include a '⌄' character).

**Comment by BingBongBonky** [comment]
Interesting suggestion, I may implement that if I can get it to work

**Comment by BingBongBonky** [comment]
So I definitely can get this to work however it would add a bit too much clutter and the dropdown wouldn't look the way that you would expect so I'm going to not implement this.
