### ISSUE TITLE
Demoman meters overlap

### ISSUE THREAD

**Issue by Spacehudhasanissue** [BingBongBonky/SpaceHUD#20]
The cannon and shield charge meters overlap. The hud will only show the loose cannon meter even if you have a shield equiped and will only show the shield when holding a melee.

**Comment by Spacehudhasanissue** [comment]
This was tested with just Loose cannon and tide turner

**Comment by BingBongBonky** [comment]
This is a feature of the game, I can't do anything about it
![image](https://github.com/BingBongBonky/SpaceHUD/assets/73761963/1f75c1b2-013a-42ad-99ed-7e4207b9e795)
![image](https://github.com/BingBongBonky/SpaceHUD/assets/73761963/ed879d2d-5c2f-46ec-b25f-3164cf5319e0)

**Comment by spacehudhasanissue2** [comment]
![20230726132025_1](https://github.com/BingBongBonky/SpaceHUD/assets/140653045/5c158c55-b8cb-45c2-94ae-71bc78b66166)

In this photo I am holding the loose cannon and have a tide turner equipped but only 1 meter shows. Without a hud these are 2 separate meters.

**Comment by spacehudhasanissue2** [comment]
![20230726132741_1](https://github.com/BingBongBonky/SpaceHUD/assets/140653045/1ca10511-caca-4c5c-a5a8-4a3d6b7bb54f)
And here the charge meter is slightly filled and only shows then the cannon meter is depleted showing that the cannon meter is on top of the shield meter

**Comment by BingBongBonky** [comment]
looks like a minmode issue then

**Comment by BingBongBonky** [comment]
This was fixed a while ago in c95f82a066ac9eed3dd0d709bcdf69acae9fc063
