### ISSUE TITLE
Flicker + font issues on linux

### ISSUE THREAD

**Issue by BingBongBonky** [BingBongBonky/SpaceHUD#7]
> i don't know if this is a linux-specific issue but the main wallpaper haves some very weird flicking issues (it doesn't loads until you open something like loadout and when it does, uhhhh Stripes Everywhere!)

![image](https://user-images.githubusercontent.com/73761963/147842724-b48937b0-b371-464e-a7a3-fd130c715b95.png)

**Comment by ProbablyNotLime** [comment]
Hi! On Arch Linux everything fine. So it could be distribution specific. 
![Screenshot_2022-01-01_14-20-27](https://user-images.githubusercontent.com/78648178/147851598-967c04ab-3f93-4988-932f-3669495e2906.png)

System info: 
NAME='EndeavourOS'
PRETTY_NAME='EndeavourOS'
ID=endeavouros
ID_LIKE=arch
BUILD_ID=2021.12.17
ANSI_COLOR="38;2;23;147;209"
HOME_URL='https://endeavouros.com'
DOCUMENTATION_URL='https://discovery.endeavouros.com'
SUPPORT_URL='https://forum.endeavouros.com'
BUG_REPORT_URL='https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports'
LOGO=endeavouros

**Comment by BingBongBonky** [comment]
That could be the case. I'll still need to fix the font issues however.

**Comment by BingBongBonky** [comment]
This should be fixed. I can't directly test it but others on Linux seem to be fine so I'll close this.
